### ISSUE TITLE
Are you still working on the book?

### ISSUE THREAD

**Issue by wpoosanguansit** [srcreigh/aluffi#3]
Hi, I came across your repo while trying to find solutions to the book.  Are you still working on the book?  Do you know where can anyone find the solutions to the book?  Thanks for your help.

**Comment by srcreigh** [comment]
Hey @wpoosanguansit, no unfortunately I am not working on the book still. I might pick it up again in the future, but for now I'm busy with work.

There is, however, a Facebook group with more than 60 members: https://www.facebook.com/groups/180191099017761/

If you have any questions about specific problems in the book, I bet if you ask there you'll get some answers.
